version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor:
        patterns:
          - "@codemirror/lang-javascript"
          - "@endo/static-module-record"
          - "@quantco/pnpm-licenses"
          - "@tsconfig/node20"
          - "change-case"
          - "dot-path-value"
          - "eventemitter3"
          - "fast-xml-parser"
          - "fuzzysearch"
          - "luxon"
          - "mediainfo.js"
          - "strip-ansi"
          - "uuid"
        update-types:
          - "major"
          - "minor"
      types:
        patterns:
          - "@babel/types"
          - "@types/*"
      build-tools:
        patterns:
          - "@vitejs/plugin-vue"
          - "@vue/*"
          - "autoprefixer"
          - "browserslist"
          - "lightningcss"
          - "postcss"
          - "rimraf"
          - "rollup-plugin-visualizer"
          - "sass"
          - "tailwindcss"
          - "terser"
          - "tsx"
          - "typescript"
          - "unplugin-turbo-console"
          - "vite-*"
          - "vite"
      vitest:
        patterns:
          - "@vitest/*"
          - "fake-indexeddb"
          - "happy-dom"
          - "playwright"
          - "timer-shim"
          - "vitest"
      vue:
        patterns:
          - "@vue/*"
          - "@vueuse/*"
          - "unplugin-vue-router"
          - "vue-*"
          - "vue"
      lint:
        patterns:
          - "@eslint*"
          - "@intlify/eslint-plugin-vue-i18n"
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "prettier*"
          - "typescript-eslint"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "@safelight/*"
