version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      vue:
        patterns:
          - "vue"
          - "vue-tsc"
          - "@vue/*"
          - "@babel/types"
      vueuse:
        patterns:
          - "@vueuse/*"
      eslint:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
    ignore:
      - dependency-name: "@safelight/*"
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-patch"]
