version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@safelight/*"
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-patch"]
