version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      vueuse:
        patterns:
          - "@vueuse/*"
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
    ignore:
      - dependency-name: "@safelight/*"
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-patch"]
