[package]
name = "sl-binding"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
dwarf-debug-info = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os', "-all"]

[lib]
crate-type = ["cdylib"]

[features]
default = ["sl-core/wasm"]
debugging = ["console_error_panic_hook"]

[dependencies]
daguerreo = { workspace = true }
sl-core = { workspace = true }

console_error_panic_hook = { workspace = true, optional = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
getrandom = { workspace = true, features = ["js"] }
nanoid = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-wasm = { workspace = true }
tsify = { workspace = true, features = ["js"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Blob"] }
