/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Monaco: typeof import('./src/components/Editor/CodeEditor/Monaco.vue')['default']
    Monitor: typeof import('./src/components/Editor/Monitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SLButton: typeof import('./src/@core/components/SLButton.vue')['default']
    SLCard: typeof import('./src/@core/components/SLCard.vue')['default']
    SLPane: typeof import('./src/@core/components/SLPane.vue')['default']
    SLSplitPanes: typeof import('./src/@core/components/SLSplitPanes.vue')['default']
    Timeline: typeof import('./src/components/Editor/Timeline/Timeline.vue')['default']
  }
}
