/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsMediaBin {
  create(item: JsBinItemType): Promise<boolean>
  getItem(path: string): Promise<JsBinItemType | null>
}

export declare class JsProject {
  constructor()
  getMediaBin(): JsMediaBin
}

export type JsBinItemType =
  | { type: 'Media', mediaPath: string, binPath: string }
  | { type: 'Directory', binPath: string }
