/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsMediaBin {
  create(path: string, item: JsBinItemType): Promise<boolean>
  getItem(path: string): Promise<JsBinItemType | null>
}

export declare class JsProject {
  constructor()
  getMediaBin(): JsMediaBin
}

export type JsBinItemType =
  | { type: 'Media', path: string, name: string }
  | { type: 'Directory', path: string, name: string }
