/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsMediaBin {
  create(project: JsProject, item: JsBinItemType): Promise<boolean>
  getItem(path: string): Promise<JsBinItemType | null>
}

export declare class JsProject {
  constructor()
  get id(): string
  getMediaBin(): JsMediaBin
}

export declare class JsTimeline {
  deleteTimelineItem(id: string): Promise<void>
  deleteTimelineItem(item: JsTimelineItem): Promise<void>
}

export declare class JsTimelineItem {

}

export type JsBinItemType =
  | { type: 'Media', mediaPath: string, binPath: string }
  | { type: 'Directory', binPath: string }

export interface JsTimelineProperties {
  /** The width of the timeline's output frame */
  width: number
  /** The height of the timeline's output frame */
  height: number
  /**
   * The duration of each frame in milliseconds
   *
   * Representing in ms does mean our FPS is capped at 1000, but that is a problem for future me
   */
  frameDuration: number
}
