[package]
name = "sl-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sl-macros = { workspace = true }

async-trait = "0.1.89"
bitflags = { version = "2.10.0", features = ["std"] }
dashmap = "6.1.0"
log = "0.4.29"
nanoid = "0.4.0"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["macros", "sync", "test-util"] }
parking_lot = "0.12.5"
