# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  pull_request:
    branches: ['main']

jobs:
  build-all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.0] # Latest LTS

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Build Darkroom
        run: pnpm build:darkroom

      - name: Build Timeline
        run: pnpm build:timeline

      - name: Build TsWebm
        run: pnpm build:tswebm

      - name: Build Safelight
        run: pnpm build:safelight
