# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
    pull_request:
        branches: ['main']

jobs:
    test-all:
        runs-on: ubuntu-latest
        if: ${{ github.triggering_actor != 'dependabot[bot]' }}

        strategy:
            matrix:
                node-version: [20.12.0] # Latest LTS

        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Enable Corepack
              run: corepack enable

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            # if: steps.playwright-cache.outputs.cache-hit != 'true'

            - name: Build Darkroom
              run: pnpm build:darkroom

            - name: Test darkroom on Chromium
              run: pnpm test:darkroom

            - name: Test darkroom on Firefox
              run: pnpm test:darkroom-firefox

            - name: Test shared
              run: pnpm test:shared

            - name: Test tswebm
              run: pnpm test:tswebm
